### ISSUE TITLE
TypeError: t is not a function

### ISSUE THREAD

**Issue by Dominic-Preap** [preflower/react-barcode-scanner#293]
Hi, we're having an error log on Next.js v14, regarding on server component despite using `use client` directive, the zbar-wasm is still load. The exmple code is below.

![image](https://github.com/user-attachments/assets/897371a5-2bc7-46ad-ab5f-331a22cd79c9)

```tsx
'use client';

import 'react-barcode-scanner/polyfill';

import { IconBulb, IconBulbOff, IconX } from '@tabler/icons-react';
import { BarcodeScanner, useTorch } from 'react-barcode-scanner';

import { BaseDialog } from '@/components/molecules/base-dialog';

import { CameraSnapFrame } from '../camera/camera-snap-frame';

interface Props {
  open: boolean;
  onClose: () => void;
  onCapture: (value: string) => void;
}

export const BarcodeScannerDialog: React.FC<Props> = props => {
  const { open, onClose, onCapture } = props;
  const [isSupportTorch, isOpen, onTorchSwitch] = useTorch();

  const Icon = isOpen ? IconBulbOff : IconBulb;
  const bulbText = isOpen ? 'Flash Off' : 'Flash On';
  return (
    <BaseDialog open={open} panelClassName="h-dvh w-dvw max-w-none p-0 -m-8 bg-black rounded-none">
      <div className="relative h-full w-full" id="camera-screen">
        <BarcodeScanner
          options={{ delay: 500, formats: ['qr_code', 'code_128'] }}
          onCapture={v => {
            onCapture(v.at(0)?.rawValue || '');
            onClose();
          }}
        />
        <CameraSnapFrame className="!aspect-h-1 !aspect-w-1" note="Scan Here" />
        <div className="absolute bottom-8 left-1/2 flex space-x-8 -translate-x-1/2">
          <ScannerButton icon={IconX} onClick={onClose} title="Close" />

          {isSupportTorch && <ScannerButton icon={Icon} onClick={onTorchSwitch} title={bulbText} />}
        </div>
      </div>
    </BaseDialog>
  );
};

interface ScannerButtonProps {
  icon: React.ElementType;
  title: string;
  onClick: () => void;
}

const ScannerButton: React.FC<ScannerButtonProps> = ({ icon: Icon, title, onClick }) => (
  <button
    onClick={onClick}
    className="flex items-center justify-center space-x-2 rounded-full bg-white px-4 py-3 shadow"
  >
    <Icon className="size-6 shrink-0 text-green" />
    <span className="text-nowrap font-medium">{title}</span>
  </button>
);

```

**Comment by preflower** [comment]
This is a error about wasm, according to [zbar-wasm issue](https://github.com/undecaf/zbar-wasm/issues/9), it's be fixed in 0.9.16, i will update version to fix it;

**Comment by Dominic-Preap** [comment]
@preflower  Sorry to ping, but any progress?

**Comment by preflower** [comment]
I apologize for previously overlooking this issue due to being too busy. After inited the Nextjs project locally, I found that I couldn’t reproduce the problem. Could you provide the corresponding dependency version numbers, as well as the version of @undercaf/zbar-wasm?

**Comment by Dominic-Preap** [comment]
@preflower Sorry for late response, here is the [minimum repository](https://github.com/Dominic-Preap/barcode-scanner-demo)

**Comment by preflower** [comment]
I fixed this problem by upgrading `@undecaf/zbar-wasm` to 0.11.0; and u can install the latest `@preflower/barcode-detector-polyfill` 0.9.21 to check it.

**Comment by Dominic-Preap** [comment]
@preflower  I tries to install `@preflower/barcode-detector-polyfill`  0.9.21  and it still show the error. But when build and run it's okay. I'm not sure if it effects anything or just error log.


 I just pushed the code in that repo you can pull and try.
![image](https://github.com/user-attachments/assets/5b0fb4c5-3f31-4fec-b6b6-c51170db75d7)

**Comment by preflower** [comment]
Not directly install `@preflower/barcode-detector-polyfill`, it's a `react-barcode-scanner` dependency, u can delete `yarn.lock` file and re-install it.
